### ISSUE TITLE
hedgedoc reverse proxy conf sample files do not actually exist anywhere

### ISSUE THREAD

**Issue by funkyfisch** [linuxserver/docker-hedgedoc#16]
I mean it's self explanatory.  hedgedoc.subdomain.proxy.sample is mentioned in the docs but does not exist on the repo listing all the samples. I couldn't find it _anywhere_ on github in fact! and the funny thing is I wanted to use it if possible, since reusing e.g. portainer's configuration does not work for hedgedoc... I'm learning nginx the past few days so I wouldn't be able to contribute to something so advanced.

**Comment by aptalca** [comment]
When the upstream project changed its name from `codimd` to `hedgedoc` we replaced all instances of `codimd` in the docs. But it seems we have forgotten to create the proxy conf for `hedgedoc`.

See the proxy conf for `codimd` here: https://github.com/linuxserver/reverse-proxy-confs/blob/master/codimd.subdomain.conf.sample
You can replace all instances of `codimd` with `hedgedoc` in there and it should work

**Comment by funkyfisch** [comment]
@aptalca Ah that makes sense actually. I can make a pull request to change this myself if you want me to.

**Comment by aptalca** [comment]
Yeah, that would be great if you can submit a PR to add a hedgehog proxy conf (leave the codimd one as is)

Thanks

**Comment by aptalca** [comment]
https://github.com/linuxserver/reverse-proxy-confs/pull/409
