### ISSUE TITLE
upgrading from codimd. add info to documentation

### ISSUE THREAD

**Issue by zettelzottel** [linuxserver/docker-hedgedoc#2]
you could add some info for those upgrading from codimd

> Error: Failed to lookup view "hedgedoc.ejs" in views directory "/opt/hedgedoc/public/views"

this error probably will come up if you have not removed the old codimd files in ./config/

**Comment by aptalca** [comment]
`you could add some info for those upgrading from codimd` 
If you have that info please PR. 
I asked but didn't get an answer: https://github.com/linuxserver/docker-codimd/issues/17#issuecomment-738870899
At this point as far as I'm concerned, this is a brand new image
