### ISSUE TITLE
Accessing HedgeDoc over HTTPS stops it from working

### ISSUE THREAD

**Issue by DanielMcAssey** [linuxserver/docker-hedgedoc#21]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

When accessing via HTTPS HedgeDoc should still work

## Current Behavior

When accessing via HTTPS it tries to load content over HTTP causing the Content Security Policy to trigger, blocking requests.

## Steps to Reproduce

1. Create Blank HedgeDoc server
2. Create an NGINX reverse proxy and use a letsencrypt certificate
3. Access hedgedoc and try to login
4.

## Environment
**OS:** Unraid
**CPU architecture:** x64
**How docker service was installed:**

From the community apps store on Unraid

## Command used to create docker container (run/create/compose/screenshot)

Not relevant

## Docker logs

Not relevant

**Comment by meno-science** [comment]
I'm seeing the same thing, and I'm also on Unraid.

[
![2021-11-16_19-32](https://user-images.githubusercontent.com/70741817/142044883-7f7fdd2f-7564-483a-b078-0957faa0634f.png)


![2021-11-16_19-29](https://user-images.githubusercontent.com/70741817/142044887-30bdc2cb-0a59-49fa-8c04-33f06c0cbabc.png)
](url)

**Comment by meno-science** [comment]
Command:

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='hedgedoc' --net='proxynet' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e HOST_HOSTNAME="potzdorf" -e HOST_CONTAINERNAME="hedgedoc" -e 'CMD_DOMAIN'='MY_URL' -e 'CMD_URL_ADDPORT'='false' -e 'CMD_DB_URL'='mysql://USER:PASSWORD@DATABASE_IP:3306/hedgedoc' -e 'CMD_PROTOCOL_USESSL'='true' -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hedgedoc-logo.png' -v '/mnt/user/appdata/hedgedoc':'/config':'rw' 'lscr.io/linuxserver/hedgedoc'

**Comment by mcking230** [comment]
@meno-science try with this environments
```
CMD_DOMAIN=mynotes.mydomain.com
CMD_URL_ADDPORT=true
CMD_PORT=443
CMD_PROTOCOL_USESSL=true
```
and change your reverse_proxy config

**Comment by cpnfeeny** [comment]
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='hedgedoc' --net='proxynet' -e TZ="Europe/Berlin" -e HOST_OS="Unraid" -e HOST_HOSTNAME="***f" -e HOST_CONTAINERNAME="hedgedoc" -e 'CMD_DOMAIN'='***' -e 'CMD_URL_ADDPORT'='false' -e 'CMD_DB_URL'='mysql://user:pass@mysql_location:3306/hedgedoc' -e 'CMD_PROTOCOL_USESSL'='true' -e 'DB_PORT'='3306' -e 'DB_USER'='hedgedoc' -e 'DB_PASS'='secret password' -e 'DB_NAME'='hedgedoc' -e 'PUID'='99' -e 'PGID'='100' -e 'UMASK'='022' -l net.unraid.docker.managed=dockerman -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hedgedoc-logo.png' -p '3000:3000/tcp' -v '/mnt/user/appdata/hedgedoc':'/config':'rw' 'lscr.io/linuxserver/hedgedoc'`

For future reference, this worked for me, in the end.

**Comment by aptalca** [comment]
as described in the readme, https access via reverse proxy requires setting `CMD_DOMAIN` to the address used, and `CMD_URL_ADDPORT` to `false`

**Comment by DanielMcAssey** [comment]
@aptalca please see my config below, still not working

![image](https://user-images.githubusercontent.com/3080979/145396930-8f3e6c2f-9a2e-4dfb-94d9-19b0f2aa300a.png)

I had to add CMD_PROTOCOL_USESSL=true. So I think the readme needs to be updated to include that

**Comment by aptalca** [comment]
Hmm, I'll have to do more tests. Last time I tested, only those two were needed.

**Comment by DanielMcAssey** [comment]
This issue prevents you from logging in, otherwise it's fine, I can access the homepage, just not login. Unless I put that other env variable

**Comment by aptalca** [comment]
Ah, gotcha, when I just tested recently, I only paid attention to all the assets on the homepage loading correctly, and created a post as a guest. I didn't try to log in.
