### ISSUE TITLE
Wrong location for the symlink to the new image upload directory

### ISSUE THREAD

**Issue by tobsz** [linuxserver/docker-hedgedoc#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

The change in the docker image to move the uploaded images from `/opt/hedgedoc/public/uploads/` to `/config/uploads/` should symlink these two directories.

## Current Behavior

At the moment the path of the symlink is `/opt/hedgedoc/public/uploads/uploads/`, which is problematic for existing uploads, since they can not be easily moved from `/opt/hedgedoc/public/uploads/` to `/config/uploads/`. Doing so results in the uploads not being found by Hedgedoc.
New uploads are also put into `/opt/hedgedoc/public/uploads/` not  `/opt/hedgedoc/public/uploads/uploads` a.k.a. `/config/uploads`.

## Environment
**OS:** Arch Linux ARM
**CPU architecture:** arm32
**How docker service was installed:** Own docker-compose.yml

**Comment by aptalca** [comment]
Post a container log

**Comment by tobsz** [comment]
Well, I'm not so certain, which container log you're interested in. When I'm `docker exec --interactive --tty hedgedoc-app-1 /bin/bash`ing into the running container, go to `/opt/hedgedoc/public/uploads/`, then there exists a symlink `uploads` pointing to  `/config/uploads/`, but when I'm now uploading a file via the Hedgedoc frontend, it will end up in  `/opt/hedgedoc/public/uploads/` not in `/opt/hedgedoc/public/uploads/uploads/ == /config/uploads/`. And manually moving it over to `/config/uploads/` results in a `"GET /uploads/foo.jpg HTTP/1.1" 404`.
The Container is used in production and updating the docker image via `docker-compose pull` followed by a container recreation already resulted twice in the deletion of the contents of `/opt/hegdedoc/public/uploads/`, although I especially created a volume to preserve the uploads. So I had to restore the image uploads from a backup.

**Comment by aptalca** [comment]
Restart the container and then do `docker logs containername`

**Comment by tobsz** [comment]
Thanks a lot for the support! Further inspecting the log information was very helpful and removing the volume for `/opt/hedgedoc/public/uploads/`in the `docker-compose.yml` before `down`ing and `up`ing again, helped solve the problem, so that the symlink pointed to the correct.
