### ISSUE TITLE
DB environment variables awkward to use (postgres unix socket)

### ISSUE THREAD

**Issue by uplighters-grays** [linuxserver/docker-hedgedoc#29]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

The custom environment variables (the ones prefixed with `DB_`) are inflexible,
and their presence requires workaround when connecting to postgres over unix socket.
------------------------------

## Expected Behavior

Usage of the upstream environment variables should be honored.
## Current Behavior

`CMD_DB_URL` is overwritten (erroneously at least in one case) for no apparent benefit, caused by this: https://github.com/linuxserver/docker-hedgedoc/blob/cc525f2/root/etc/services.d/hedgedoc/run#L3-L9
## Steps to Reproduce

1. Install postgresql on host, expose it over unix socket
2. Run `hedgedoc` container with the directory holding the socket exposed to it, use the relevant envvars from upstream to configure the db (see below). `CMD_DB_URL` is not set in this case, as it doesn't really make sense, [Sequelize expects the socket directory to simply be given as a host](https://sequelize.org/v5/class/lib/sequelize.js~sequelize) (`CMD_DB_HOST`).
(Also the `DB_*` variables provided by the LinuxServer image cannot be used at all, since if they are set, the LS run script will just assume mysql, and again, a URL cannot be used in this case. To be fair this is part of the documentation, although I did at first think "mysql" was just there by mistake)
3. Watch as `CMD_DB_URL` gets forcefully overridden because it does not exist
4. Container will run using "fallback" sqlite db

## Environment
**OS:** GNU/Linux
**CPU architecture:** arm64
**How docker service was installed:**
distribution `podman`

## Command used to create docker container (run/create/compose/screenshot)

    # podman run -p 3000:3000 -v /run/postgresql:/run/postgresql \
    -e PUID=972 -e PGID=972 \
    -e CMD_DB_DIALECT=postgres -e CMD_DB_HOST=/run/postgresql/ \
    -e CMD_DB_DATABASE=hedgedoc -e CMD_DB_USERNAME=hedgedoc \
    -e CMD_DOMAIN=example.com -e CMD_PROTOCOL_USESSL=true -e CMD_PORT=3000 \
    lscr.io/linuxserver/hedgedoc 

## Docker logs

N/A

**Comment by uplighters-grays** [comment]
(Note that trying to fix the variables in the config file does not work as environment variables have precedence) 

The workaround is to specify `-e CMD_DB_URL=''`, causing the second conditional in the run script to evaluate as false. This is possible due to the missing colon in the parameter expansion, which is possibly incidental.
In my opinion, the `DB_*` variables should be done away with in favor of the upstream ones, given those serve the same purpose and do not make incorrect assumptions such that the db is mysql or that a url must be present.

**Comment by aptalca** [comment]
When we designed this image, hedgedoc didn't support postgres. It was either sqlite or mysql/mariadb.

We would need to add it as a new feature

**Comment by uplighters-grays** [comment]
Regardless of whether we consider this a "feature" of this image (I would expect packaging of software to not affect functionality), what solutions are up for consideration? My proposal would simply get rid of the offending lines. This would however mean that the mysql specific code would also need to go.

Well, if you really wanted you could just use the upstream variables instead to try and query the db, but you would need additional code to parse the variables, possibly decide what to do on each db and in case the host is given as a unix socket (which I am not sure is a good idea to try parse), not construct a url.

Alternatively, you could keep your variables and just assign them to the upstream ones directly if set instead of constructing a url, since sequelize will still make the db connection anyways.

**Comment by aptalca** [comment]
This image was published long before the name `hedgedoc` existed. It currently supports sqlite and mysql/mariadb.

Anything else would require updates, but without breaking existing users' setups.

I personally have a long to do list and little interest in postgres support in this image. Other team members may have different priorities. In any case, PRs welcome.
