### ISSUE TITLE
Pull access denied for ghcr.io/linuxserver/hedgedoc

### ISSUE THREAD

**Issue by nicholaswilde** [linuxserver/docker-hedgedoc#3]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
When running the `docker-compose.yaml` file, the server should start when pulling from `ghcr.io/linuxserver/hedgedoc`

## Current Behavior
When pulling from `ghcr.io/linuxserver/hedgedoc`, I get the following error:
```
Pulling hedgedoc (ghcr.io/linuxserver/hedgedoc:latest)...
ERROR: pull access denied for ghcr.io/linuxserver/hedgedoc, repository does not exist or may require 'docker login': denied: permission_denied: read_package
```
I think the package from `ghcr.io` is set to private and not public.

## Steps to Reproduce

1. create `docker-compose.yaml` file from the `README.md`
2. `$ docker-compose up`

## Environment
**OS:**
```
$ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
HYPRIOT_DEVICE="Raspberry Pi"
HYPRIOT_IMAGE_VERSION="v1.12.3"
```
**CPU architecture:** x86_64/arm32/arm64
```
$ uname -a
Linux worker-02 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux
```
Hypriot came preinstalled with Docker

## Command used to create docker container (run/create/compose/screenshot)
`$ docker-compose up`

## Docker logs
```
Pulling hedgedoc (ghcr.io/linuxserver/hedgedoc:latest)...
ERROR: pull access denied for ghcr.io/linuxserver/hedgedoc, repository does not exist or may require 'docker login': denied: permission_denied: read_package
```

**Comment by aptalca** [comment]
Known issue with the github registry, waiting for a fix: https://github.community/t/cant-make-internal-ghcr-images-public/151900
In the meantime, you can pull from dockerhub at `linuxserver/hedgedoc`

**Comment by aptalca** [comment]
Issue is solved on the github side and the image is public on ghcr

**Comment by Yassine2217** [comment]
i have the same thing happend to plex any idea please
2022-01-16 09:03:24 (info): Unable to update container /Plex, err='Error response from daemon: pull access denied for ghcr.io/linuxserver/plex, repository does not exist or may require 'docker login': denied: requested access to the resource is denied'. Proceeding to next.
