### ISSUE TITLE
FILE__ variables get appended a newline character \n or %0A

### ISSUE THREAD

**Issue by DennisGaida** [linuxserver/docker-hedgedoc#31]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
`FILE__` environment variables should not get a newline character appended

## Current Behavior
Using two environment variable replacements (`FILE__CMD_OAUTH2_CLIENT_ID` and `FILE__CMD_OAUTH2_CLIENT_SECRET`. They both get appended `\n` or `%0A` which of course breaks functionality for OAUTH in this image.

Using the original environment variables (i.e. `CMD_OAUTH2_CLIENT_ID`) without using docker secrets works. Unfortunately going back a version doesn't help since this seems to be a change in the used linuxserver base image (that is responsible for the  `FILE__` environment variable magic).

**Comment by Roxedus** [comment]
The newline is most likely present in your file. Echo and nano does append this by default, to name a few

**Comment by aptalca** [comment]
if the command prompt ends up on the next line after cat, your file has a trailing newline

**Comment by Roxedus** [comment]
This image does not handle secrets differently than any other of ours. 
I was pretty sure there was a note about this scenario on the secret docs, but I dont see it now. This commit is however relevant, the docs also still use printf for the same reason. https://github.com/docker/docker.github.io/commit/373214ff986076a039a72593c5187a3943b06309
