### ISSUE TITLE
[BUG] multi-line paste is broken specifically in linuxserver image (not upstream)

### ISSUE THREAD

**Issue by mtoupsUNO** [linuxserver/docker-hedgedoc#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Very annoying problem with pasting text into documents was originally reported here https://github.com/hedgedoc/hedgedoc/issues/4103

I can confirm that when switching from `lscr.io/linuxserver/hedgedoc:latest` to `quay.io/hedgedoc/hedgedoc:latest` the problem goes away

So this bug is specific to the linuxserver version of hedgedoc, not upstream

### Expected Behavior

We should be able to paste text (of more than a trivial amount) to the web app without having it fail (and switch to "offline" requiring the user to log back in again)

### Steps To Reproduce

Browse to http://server-ip:port/
Login with email and password
Open the Features note editor
Select all
Create a new note
Paste the copied content of the Features note
Preview remains empty and I can no longer type in the editor

### CPU architecture

x86-64

### Docker creation

```bash
This is my docker-compose:
`version: "3"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    hostname: mariadb
    restart: unless-stopped
    volumes:
      - mariadb-config:/config
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=hedgedoc
      - MYSQL_USER=hedgedoc
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  hedgedoc:
    image: lscr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    hostname: hedgedoc
    depends_on:
      - mariadb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=hedgedoc
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=hedgedoc
      - CMD_DOMAIN=${SERVER_IP}
      - CMD_URL_ADDPORT=true #optional
      - CMD_PROTOCOL_USESSL=false #optional
      - CMD_PORT=5805 #optional
    volumes:
      - hedgedoc-config:/config
    ports:
      - 5805:5805
    restart: unless-stopped`
```

### Container logs

```bash
HedgeDoc version: 1.97
```

**Comment by Roxedus** [comment]
Please add container logs.

**Comment by ajitam** [comment]
I have the same issue. Logs (when error occurs) 
```
doc-hedgedoc-1          | 2023-06-02T13:07:24.004Z warn:        Session secret not set. Using random generated one. Please set `sessionSecret` in your config.json file. All users will be logged out.
doc-hedgedoc-1          | 2023-06-02T13:07:25.316Z info:        All migrations performed successfully
doc-hedgedoc-1          | 2023-06-02T13:07:25.337Z info:        HTTP Server listening at 0.0.0.0:3000
```

if you then add `CMD_SESSION_SECRET` into `docker-compose.yaml` is a bit better but container still restarts. On frontend you see this on top right status is `OFFLINE` for a few seconds, but at list you don't get logged out.

I do not remember this happening a few versions back (and I never had `CMD_SESSION_SECRET`) setup.

**Comment by ajitam** [comment]
(also for me) switch to `quay.io/hedgedoc/hedgedoc:latest` and it works (no error when paste)
