### ISSUE TITLE
Update image to 1.7.1

### ISSUE THREAD

**Issue by TheGreatestJannet** [linuxserver/docker-hedgedoc#4]
A security update came out for Hedgedoc: https://github.com/hedgedoc/hedgedoc/releases/tag/1.7.1

Is this image going to be updated to the latest version?

**Comment by nemchik** [comment]
It looks like our version check that triggers updates is failing. We'll look into it.

**Comment by aptalca** [comment]
Due to the following issue, or external trigger is failing (and the image is not public on ghcr): https://github.community/t/cant-make-internal-ghcr-images-public/151900

I'll trigger a manual build and it should be pushed to docker hub

**Comment by TheGreatestJannet** [comment]
Thank you!
